language: csharp
solution: "BasicMod/BasicMod.sln"

os: linux
matrix:
  include:
    - dist: bionic
    - dist: xenial
mono: latest

install:
  - sudo apt-get install mono-xbuild
  - nuget restore BasicMod/BasicMod.sln
script:
  - xbuild /p:Configuration=Release BasicMod/BasicMod.sln
