language: csharp
solution: "BasicMod/BasicMod.sln"

os: linux
matrix:
  include:
    - dist: bionic
    - dist: xenial
mono: latest

install:
  - ./ci/set_SV_path.sh "./build" 
  - nuget restore BasicMod/BasicMod.sln
script:
  - msbuild /p:Configuration=Release BasicMod/BasicMod.sln
