language: csharp
solution: "BasicMod/BasicMod.sln"

os: linux
dist:
  - bionic
  - xenial
mono: latest
install:
  - nuget restore BasicMod/BasicMod.sln
script:
  - msbuild /p:Configuration=Release BasicMod/BasicMod.sln
