language: csharp
solution: "BasicMod/BasicMod.sln"

os: linux
matrix:
  include:
    - dist: bionic
    - dist: xenial
mono: latest

install:
  - mkdir -p "~/.steam/root/steamapps/common/Stardew Valley/"
  - nuget restore BasicMod/BasicMod.sln
script:
  - msbuild /p:Configuration=Release BasicMod/BasicMod.sln
