language: csharp
solution: "BasicMod/BasicMod.sln"

os: linux
dist:
  - bionic
  - xenial
mono: latest
install:
  - sudo apt-get install xbuild
  - nuget restore BasicMod/BasicMod.sln
script:
  - xbuild /p:Configuration=Release BasicMod/BasicMod.sln
